# Generated by Django 5.2.7 on 2025-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
                ('tasks', models.ManyToManyField(blank=True, to='task_manager.task')),
            ],
        ),
    ]
