# Generated by Django 5.2.7 on 2025-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_week_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_target',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
