# Generated by Django 5.2.7 on 2025-11-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_week_target_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_target',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
