# Generated by Django 5.2.7 on 2025-11-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_week_target_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_target',
            name='deadline',
            field=models.TextField(blank=True),
        ),
    ]
