# Generated by Django 5.2.7 on 2025-11-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_alter_week_target_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week_target',
            name='tasks',
        ),
        migrations.AddField(
            model_name='week_target',
            name='parent_task',
            field=models.TextField(blank=True),
        ),
    ]
